// Compiles src/*.sol with solc-js (no network, no Foundry needed) and writes typed TS artifacts
// (`abi as const` + bytecode) that viem consumes directly.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const solc = require("solc");
const here = path.dirname(fileURLToPath(import.meta.url));

const sources = {};
for (const f of readdirSync(path.join(here, "src")).filter((f) => f.endsWith(".sol"))) {
  sources[`src/${f}`] = { content: readFileSync(path.join(here, "src", f), "utf8") };
}

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "shanghai",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

function findImport(p) {
  try {
    return { contents: readFileSync(require.resolve(p), "utf8") };
  } catch {
    return { error: `not found: ${p}` };
  }
}

const out = JSON.parse(solc.compile(JSON.stringify(input), { import: findImport }));
const errors = (out.errors ?? []).filter((e) => e.severity === "error");
for (const e of out.errors ?? []) console.error(e.formattedMessage);
if (errors.length) process.exit(1);

mkdirSync(path.join(here, "artifacts"), { recursive: true });
for (const [file, contracts] of Object.entries(out.contracts)) {
  if (!file.startsWith("src/")) continue;
  for (const [name, c] of Object.entries(contracts)) {
    const body =
      `// GENERATED by contracts/build.mjs from ${file}. Do not edit.\n` +
      `export const abi = ${JSON.stringify(c.abi, null, 2)} as const;\n\n` +
      `export const bytecode = "0x${c.evm.bytecode.object}" as const;\n`;
    writeFileSync(path.join(here, "artifacts", `${name}.ts`), body);
    console.log(`built ${name} (${c.evm.bytecode.object.length / 2} bytes)`);
  }
}
